// !!! This file will be generated by ./tool/create.js auto

import Charts from './Charts';
import CountDown from './CountDown';
import DescriptionList from './DescriptionList';
import Exception from './Exception';
import FooterToolbar from './FooterToolbar';
import GlobalFooter from './GlobalFooter';
import HeaderSearch from './HeaderSearch';
import NoticeIcon from './NoticeIcon';
import PageHeader from './PageHeader';
import Result from './Result';
import TagSelect from './TagSelect';
import AvatarList from './AvatarList';
import Trend from './Trend';
import NumberInfo from './NumberInfo';
import Ellipsis from './Ellipsis';
import Authorized from './Authorized';
import Login from './Login';

export default {
  Charts,
  CountDown,
  DescriptionList,
  Exception,
  FooterToolbar,
  GlobalFooter,
  HeaderSearch,
  NoticeIcon,
  PageHeader,
  Result,
  TagSelect,
  AvatarList,
  Trend,
  NumberInfo,
  Ellipsis,
  Authorized,
  Login,
};
