webpackJsonp([42],{

/***/ 2385:
/***/ (function(module, exports) {

module.exports = {
  "content": [
    "section",
    [
      "p",
      "权限组件，通过比对现有权限与准入权限，决定相关元素的展示。"
    ]
  ],
  "meta": {
    "title": {
      "en-US": "Authorized",
      "zh-CN": "Authorized"
    },
    "subtitle": "权限",
    "cols": 1,
    "order": 15,
    "filename": "scaffold/src/components/Authorized/index.md"
  },
  "toc": [
    "ul",
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#API",
          "title": "API"
        },
        "API"
      ]
    ]
  ],
  "api": [
    "section",
    [
      "h2",
      "API"
    ],
    [
      "h3",
      "RenderAuthorized"
    ],
    [
      "p",
      [
        "code",
        "RenderAuthorized: (currentAuthority: string | () => string) => Authorized"
      ]
    ],
    [
      "p",
      "权限组件默认 export RenderAuthorized 函数，它接收当前权限作为参数，返回一个权限对象，该对象提供以下几种使用方式。"
    ],
    [
      "h3",
      "Authorized"
    ],
    [
      "p",
      "最基础的权限控制。"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "children"
          ],
          [
            "td",
            "正常渲染的元素，权限判断通过时展示"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "authority"
          ],
          [
            "td",
            "准入权限/权限判断"
          ],
          [
            "td",
            [
              "code",
              "string | array | Promise | (currentAuthority) => boolean | Promise"
            ]
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "noMatch"
          ],
          [
            "td",
            "权限异常渲染元素，权限判断不通过时展示"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ]
      ]
    ],
    [
      "h3",
      "Authorized.AuthorizedRoute"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "authority"
          ],
          [
            "td",
            "准入权限/权限判断"
          ],
          [
            "td",
            [
              "code",
              "string | array | Promise | (currentAuthority) => boolean | Promise"
            ]
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "redirectPath"
          ],
          [
            "td",
            "权限异常时重定向的页面路由"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "-"
          ]
        ]
      ]
    ],
    [
      "p",
      "其余参数与 ",
      [
        "code",
        "Route"
      ],
      " 相同。"
    ],
    [
      "h3",
      "Authorized.Secured"
    ],
    [
      "p",
      "注解方式，",
      [
        "code",
        "@Authorized.Secured(authority, error)"
      ]
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "authority"
          ],
          [
            "td",
            "准入权限/权限判断"
          ],
          [
            "td",
            [
              "code",
              "string | Promise | (currentAuthority) => boolean | Promise"
            ]
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "error"
          ],
          [
            "td",
            "权限异常时渲染元素"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            [
              "exception",
              {
                "type": "403"
              }
            ]
          ]
        ]
      ]
    ],
    [
      "h3",
      "Authorized.check"
    ],
    [
      "p",
      "函数形式的 Authorized，用于某些不能被 HOC 包裹的组件。 ",
      [
        "code",
        "Authorized.check(authority, target, Exception)"
      ],
      "\n注意：传入一个 Promise 时，无论正确还是错误返回的都是一个 ReactClass。"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "authority"
          ],
          [
            "td",
            "准入权限/权限判断"
          ],
          [
            "td",
            [
              "code",
              "string | Promise | (currentAuthority) => boolean | Promise"
            ]
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "target"
          ],
          [
            "td",
            "权限判断通过时渲染的元素"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "Exception"
          ],
          [
            "td",
            "权限异常时渲染元素"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ]
      ]
    ]
  ]
};

/***/ })

});