webpackJsonp([23],{

/***/ 2415:
/***/ (function(module, exports) {

module.exports = {
  "content": [
    "section",
    [
      "p",
      "用在导航工具栏上，作为整个产品统一的通知中心。"
    ]
  ],
  "meta": {
    "title": "NoticeIcon",
    "subtitle": "通知菜单",
    "cols": 1,
    "order": 9,
    "filename": "scaffold/src/components/NoticeIcon/index.zh-CN.md"
  },
  "toc": [
    "ul",
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#API",
          "title": "API"
        },
        "API"
      ]
    ]
  ],
  "api": [
    "section",
    [
      "h2",
      "API"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "count"
          ],
          [
            "td",
            "图标上的消息总数"
          ],
          [
            "td",
            "number"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "bell"
          ],
          [
            "td",
            "translate this please -> Change the bell Icon"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            [
              "code",
              "<Icon type='bell' />"
            ]
          ]
        ],
        [
          "tr",
          [
            "td",
            "loading"
          ],
          [
            "td",
            "弹出卡片加载状态"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onClear"
          ],
          [
            "td",
            "点击清空按钮的回调"
          ],
          [
            "td",
            "function(tabTitle)"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onItemClick"
          ],
          [
            "td",
            "点击列表项的回调"
          ],
          [
            "td",
            "function(item, tabProps)"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onTabChange"
          ],
          [
            "td",
            "切换页签的回调"
          ],
          [
            "td",
            "function(tabTitle)"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "popupAlign"
          ],
          [
            "td",
            "弹出卡片的位置配置"
          ],
          [
            "td",
            "Object ",
            [
              "a",
              {
                "title": null,
                "href": "https://github.com/yiminghe/dom-align#alignconfig-object-details"
              },
              "alignConfig"
            ]
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onPopupVisibleChange"
          ],
          [
            "td",
            "弹出卡片显隐的回调"
          ],
          [
            "td",
            "function(visible)"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "popupVisible"
          ],
          [
            "td",
            "控制弹层显隐"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "locale"
          ],
          [
            "td",
            "默认文案"
          ],
          [
            "td",
            "Object"
          ],
          [
            "td",
            [
              "code",
              "{ emptyText: '暂无数据', clear: '清空' }"
            ]
          ]
        ]
      ]
    ],
    [
      "h3",
      "NoticeIcon.Tab"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "title"
          ],
          [
            "td",
            "消息分类的页签标题"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "list"
          ],
          [
            "td",
            "列表数据，格式参照下表"
          ],
          [
            "td",
            "Array"
          ],
          [
            "td",
            [
              "code",
              "[]"
            ]
          ]
        ],
        [
          "tr",
          [
            "td",
            "showClear"
          ],
          [
            "td",
            "是否显示清空按钮"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "true"
          ]
        ],
        [
          "tr",
          [
            "td",
            "emptyText"
          ],
          [
            "td",
            "针对每个 Tab 定制空数据文案"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "emptyImage"
          ],
          [
            "td",
            "针对每个 Tab 定制空数据图片"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "-"
          ]
        ]
      ]
    ],
    [
      "h3",
      "Tab data"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "参数"
          ],
          [
            "th",
            "说明"
          ],
          [
            "th",
            "类型"
          ],
          [
            "th",
            "默认值"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "avatar"
          ],
          [
            "td",
            "头像图片链接"
          ],
          [
            "td",
            "string ",
            "|",
            " ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "title"
          ],
          [
            "td",
            "标题"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "description"
          ],
          [
            "td",
            "描述信息"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "datetime"
          ],
          [
            "td",
            "时间戳"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "extra"
          ],
          [
            "td",
            "额外信息，在列表项右上角"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ]
      ]
    ]
  ]
};

/***/ })

});