webpackJsonp([24],{

/***/ 2431:
/***/ (function(module, exports) {

module.exports = {
  "content": [
    "section",
    [
      "p",
      "用在导航工具栏上，作为整个产品统一的通知中心。"
    ]
  ],
  "meta": {
    "title": "NoticeIcon",
    "subtitle": "Notification Menu",
    "cols": 1,
    "order": 9,
    "filename": "scaffold/src/components/NoticeIcon/index.en-US.md"
  },
  "toc": [
    "ul",
    [
      "li",
      [
        "a",
        {
          "className": "bisheng-toc-h2",
          "href": "#API",
          "title": "API"
        },
        "API"
      ]
    ]
  ],
  "api": [
    "section",
    [
      "h2",
      "API"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "Property"
          ],
          [
            "th",
            "Description"
          ],
          [
            "th",
            "Type"
          ],
          [
            "th",
            "Default"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "count"
          ],
          [
            "td",
            "Total number of messages"
          ],
          [
            "td",
            "number"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "bell"
          ],
          [
            "td",
            "Change the bell Icon"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            [
              "code",
              "<Icon type='bell' />"
            ]
          ]
        ],
        [
          "tr",
          [
            "td",
            "loading"
          ],
          [
            "td",
            "Popup card loading status"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "false"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onClear"
          ],
          [
            "td",
            "Click to clear button the callback"
          ],
          [
            "td",
            "function(tabTitle)"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onItemClick"
          ],
          [
            "td",
            "Click on the list item's callback"
          ],
          [
            "td",
            "function(item, tabProps)"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onTabChange"
          ],
          [
            "td",
            "Switching callbacks for tabs"
          ],
          [
            "td",
            "function(tabTitle)"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "popupAlign"
          ],
          [
            "td",
            "Popup card location configuration"
          ],
          [
            "td",
            "Object ",
            [
              "a",
              {
                "title": null,
                "href": "https://github.com/yiminghe/dom-align#alignconfig-object-details"
              },
              "alignConfig"
            ]
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "onPopupVisibleChange"
          ],
          [
            "td",
            "Popup Card Showing or Hiding Callbacks"
          ],
          [
            "td",
            "function(visible)"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "popupVisible"
          ],
          [
            "td",
            "Popup card display state"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "locale"
          ],
          [
            "td",
            "Default message text"
          ],
          [
            "td",
            "Object"
          ],
          [
            "td",
            [
              "code",
              "{ emptyText: '暂无数据', clear: '清空' }"
            ]
          ]
        ]
      ]
    ],
    [
      "h3",
      "NoticeIcon.Tab"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "Property"
          ],
          [
            "th",
            "Description"
          ],
          [
            "th",
            "Type"
          ],
          [
            "th",
            "Default"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "title"
          ],
          [
            "td",
            "header for message Tab"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "list"
          ],
          [
            "td",
            "List data, format refer to the following table"
          ],
          [
            "td",
            "Array"
          ],
          [
            "td",
            [
              "code",
              "[]"
            ]
          ]
        ],
        [
          "tr",
          [
            "td",
            "showClear"
          ],
          [
            "td",
            "Clear button display status"
          ],
          [
            "td",
            "boolean"
          ],
          [
            "td",
            "true"
          ]
        ],
        [
          "tr",
          [
            "td",
            "emptyText"
          ],
          [
            "td",
            "message text when list is empty"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "emptyImage"
          ],
          [
            "td",
            "image  when list is empty"
          ],
          [
            "td",
            "string"
          ],
          [
            "td",
            "-"
          ]
        ]
      ]
    ],
    [
      "h3",
      "Tab data"
    ],
    [
      "table",
      [
        "thead",
        [
          "tr",
          [
            "th",
            "Property"
          ],
          [
            "th",
            "Description"
          ],
          [
            "th",
            "Type"
          ],
          [
            "th",
            "Default"
          ]
        ]
      ],
      [
        "tbody",
        [
          "tr",
          [
            "td",
            "avatar"
          ],
          [
            "td",
            "avatar img url"
          ],
          [
            "td",
            "string ",
            "|",
            " ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "title"
          ],
          [
            "td",
            "title"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "description"
          ],
          [
            "td",
            "description info"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "datetime"
          ],
          [
            "td",
            "Timestamps"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ],
        [
          "tr",
          [
            "td",
            "extra"
          ],
          [
            "td",
            "Additional information in the upper right corner of the list item"
          ],
          [
            "td",
            "ReactNode"
          ],
          [
            "td",
            "-"
          ]
        ]
      ]
    ]
  ]
};

/***/ })

});